public enum Country {
    AFG("AFG", "Afeganistão"),
    ZAF("ZAF", "África do Sul"),
    ALB("ALB", "Albânia"),
    DEU("DEU", "Alemanha"),
    AND("AND", "Andorra"),
    AGO("AGO", "Angola"),
    AIA("AIA", "Anguilla"),
    ATA("ATA", "Antártida"),
    ATG("ATG", "Antígua e Barbuda"),
    ANT("ANT", "Antilhas Holandesas"),
    SAU("SAU", "Arábia Saudita"),
    DZA("DZA", "Argélia"),
    ARG("ARG", "Argentina"),
    ARM("ARM", "Armênia"),
    ABW("ABW", "Aruba"),
    AUS("AUS", "Austrália"),
    AUT("AUT", "Áustria"),
    AZE("AZE", "Azerbaijão"),
    BHS("BHS", "Bahamas"),
    BHR("BHR", "Bahrein"),
    BGD("BGD", "Bangladesh"),
    BRB("BRB", "Barbados"),
    BLR("BLR", "Belarus"),
    BEL("BEL", "Bélgica"),
    BLZ("BLZ", "Belize"),
    BEN("BEN", "Benin"),
    BMU("BMU", "Bermudas"),
    BOL("BOL", "Bolívia"),
    BIH("BIH", "Bósnia-Herzegóvina"),
    BWA("BWA", "Botsuana"),
    BRA("BRA", "Brasil"),
    BRN("BRN", "Brunei"),
    BGR("BGR", "Bulgária"),
    BFA("BFA", "Burkina Fasso"),
    BDI("BDI", "Burundi"),
    BTN("BTN", "Butão"),
    CPV("CPV", "Cabo Verde"),
    CMR("CMR", "Camarões"),
    KHM("KHM", "Camboja"),
    CAN("CAN", "Canadá"),
    KAZ("KAZ", "Cazaquistão"),
    TCD("TCD", "Chade"),
    CHL("CHL", "Chile"),
    CHN("CHN", "China"),
    CYP("CYP", "Chipre"),
    SGP("SGP", "Cingapura"),
    COL("COL", "Colômbia"),
    COG("COG", "Congo"),
    PRK("PRK", "Coréia do Norte"),
    KOR("KOR", "Coréia do Sul"),
    CIV("CIV", "Costa do Marfim"),
    CRI("CRI", "Costa Rica"),
    HRV("HRV", "Croácia (Hrvatska)"),
    CUB("CUB", "Cuba"),
    DNK("DNK", "Dinamarca"),
    DJI("DJI", "Djibuti"),
    DMA("DMA", "Dominica"),
    EGY("EGY", "Egito"),
    SLV("SLV", "El Salvador"),
    ARE("ARE", "Emirados Árabes Unidos"),
    ECU("ECU", "Equador"),
    ERI("ERI", "Eritréia"),
    SVK("SVK", "Eslováquia"),
    SVN("SVN", "Eslovênia"),
    ESP("ESP", "Espanha"),
    USA("USA", "Estados Unidos"),
    EST("EST", "Estônia"),
    ETH("ETH", "Etiópia"),
    FJI("FJI", "Fiji"),
    PHL("PHL", "Filipinas"),
    FIN("FIN", "Finlândia"),
    FRA("FRA", "França"),
    GAB("GAB", "Gabão"),
    GMB("GMB", "Gâmbia"),
    GHA("GHA", "Gana"),
    GEO("GEO", "Geórgia"),
    GIB("GIB", "Gibraltar"),
    GBR("GBR", "Grã-Bretanha (Reino Unido, UK)"),
    GRD("GRD", "Granada"),
    GRC("GRC", "Grécia"),
    GRL("GRL", "Groelândia"),
    GLP("GLP", "Guadalupe"),
    GUM("GUM", "Guam (Território dos Estados Unidos)"),
    GTM("GTM", "Guatemala"),
    GGY("GGY", "Guernsey"),
    GUY("GUY", "Guiana"),
    GUF("GUF", "Guiana Francesa"),
    GIN("GIN", "Guiné"),
    GNQ("GNQ", "Guiné Equatorial"),
    GNB("GNB", "Guiné-Bissau"),
    HTI("HTI", "Haiti"),
    NLD("NLD", "Holanda"),
    HND("HND", "Honduras"),
    HKG("HKG", "Hong Kong"),
    HUN("HUN", "Hungria"),
    YEM("YEM", "Iêmen"),
    BVT("BVT", "Ilha Bouvet (Território da Noruega)"),
    IMN("IMN", "Ilha do Homem"),
    CXR("CXR", "Ilha Natal"),
    PCN("PCN", "Ilha Pitcairn"),
    REU("REU", "Ilha Reunião"),
    ALA("ALA", "Ilhas Aland"),
    CYM("CYM", "Ilhas Cayman"),
    CCK("CCK", "Ilhas Cocos"),
    COM("COM", "Ilhas Comores"),
    COK("COK", "Ilhas Cook"),
    FRO("FRO", "Ilhas Faroes"),
    FLK("FLK", "Ilhas Falkland (Malvinas)"),
    SGS("SGS", "Ilhas Geórgia do Sul e Sandwich do Sul"),
    HMD("HMD", "Ilhas Heard e McDonald (Território da Austrália)"),
    MNP("MNP", "Ilhas Marianas do Norte"),
    MHL("MHL", "Ilhas Marshall"),
    UMI("UMI", "Ilhas Menores dos Estados Unidos"),
    NFK("NFK", "Ilhas Norfolk"),
    SYC("SYC", "Ilhas Seychelles"),
    SLB("SLB", "Ilhas Solomão"),
    SJM("SJM", "Ilhas Svalbard e Jan Mayen"),
    TKL("TKL", "Ilhas Tokelau"),
    TCA("TCA", "Ilhas Turks e Caicos"),
    VIR("VIR", "Ilhas Virgens (Estados Unidos)"),
    VGB("VGB", "Ilhas Virgens (Inglaterra)"),
    WLF("WLF", "Ilhas Wallis e Futuna"),
    IND("IND", "índia"),
    IDN("IDN", "Indonésia"),
    IRN("IRN", "Irã"),
    IRQ("IRQ", "Iraque"),
    IRL("IRL", "Irlanda"),
    ISL("ISL", "Islândia"),
    ISR("ISR", "Israel"),
    ITA("ITA", "Itália"),
    JAM("JAM", "Jamaica"),
    JPN("JPN", "Japão"),
    JEY("JEY", "Jersey"),
    JOR("JOR", "Jordânia"),
    KEN("KEN", "Kênia"),
    KIR("KIR", "Kiribati"),
    KWT("KWT", "Kuait"),
    LAO("LAO", "Laos"),
    LVA("LVA", "Látvia"),
    LSO("LSO", "Lesoto"),
    LBN("LBN", "Líbano"),
    LBR("LBR", "Libéria"),
    LBY("LBY", "Líbia"),
    LIE("LIE", "Liechtenstein"),
    LTU("LTU", "Lituânia"),
    LUX("LUX", "Luxemburgo"),
    MAC("MAC", "Macau"),
    MKD("MKD", "Macedônia (República Yugoslava)"),
    MDG("MDG", "Madagascar"),
    MYS("MYS", "Malásia"),
    MWI("MWI", "Malaui"),
    MDV("MDV", "Maldivas"),
    MLI("MLI", "Mali"),
    MLT("MLT", "Malta"),
    MAR("MAR", "Marrocos"),
    MTQ("MTQ", "Martinica"),
    MUS("MUS", "Maurício"),
    MRT("MRT", "Mauritânia"),
    MYT("MYT", "Mayotte"),
    MEX("MEX", "México"),
    FSM("FSM", "Micronésia"),
    MOZ("MOZ", "Moçambique"),
    MDA("MDA", "Moldova"),
    MCO("MCO", "Mônaco"),
    MNG("MNG", "Mongólia"),
    MNE("MNE", "Montenegro"),
    MSR("MSR", "Montserrat"),
    MMR("MMR", "Myanma"),
    NAM("NAM", "Namíbia"),
    NRU("NRU", "Nauru"),
    NPL("NPL", "Nepal"),
    NIC("NIC", "Nicarágua"),
    NER("NER", "Níger"),
    NGA("NGA", "Nigéria"),
    NIU("NIU", "Niue"),
    NOR("NOR", "Noruega"),
    NCL("NCL", "Nova Caledônia"),
    NZL("NZL", "Nova Zelândia"),
    OMN("OMN", "Omã"),
    PLW("PLW", "Palau"),
    PAN("PAN", "Panamá"),
    PNG("PNG", "Papua-Nova Guiné"),
    PAK("PAK", "Paquistão"),
    PRY("PRY", "Paraguai"),
    PER("PER", "Peru"),
    PYF("PYF", "Polinésia Francesa"),
    POL("POL", "Polônia"),
    PRI("PRI", "Porto Rico"),
    PRT("PRT", "Portugal"),
    QAT("QAT", "Qatar"),
    KGZ("KGZ", "Quirguistão"),
    CAF("CAF", "República Centro-Africana"),
    COD("COD", "República Democrática do Congo"),
    DOM("DOM", "República Dominicana"),
    CZE("CZE", "República Tcheca"),
    ROM("ROM", "Romênia"),
    RWA("RWA", "Ruanda"),
    RUS("RUS", "Rússia (antiga URSS) - Federação Russa"),
    ESH("ESH", "Saara Ocidental"),
    VCT("VCT", "Saint Vincente e Granadinas"),
    ASM("ASM", "Samoa Americana"),
    WSM("WSM", "Samoa Ocidental"),
    SMR("SMR", "San Marino"),
    SHN("SHN", "Santa Helena"),
    LCA("LCA", "Santa Lúcia"),
    BLM("BLM", "São Bartolomeu"),
    KNA("KNA", "São Cristóvão e Névis"),
    MAF("MAF", "São Martim"),
    STP("STP", "São Tomé e Príncipe"),
    SEN("SEN", "Senegal"),
    SLE("SLE", "Serra Leoa"),
    SRB("SRB", "Sérvia"),
    SYR("SYR", "Síria"),
    SOM("SOM", "Somália"),
    LKA("LKA", "Sri Lanka"),
    SPM("SPM", "St. Pierre and Miquelon"),
    SWZ("SWZ", "Suazilândia"),
    SDN("SDN", "Sudão"),
    SWE("SWE", "Suécia"),
    CHE("CHE", "Suíça"),
    SUR("SUR", "Suriname"),
    TJK("TJK", "Tadjiquistão"),
    THA("THA", "Tailândia"),
    TWN("TWN", "Taiwan"),
    TZA("TZA", "Tanzânia"),
    IOT("IOT", "Território Britânico do Oceano índico"),
    ATF("ATF", "Territórios do Sul da França"),
    PSE("PSE", "Territórios Palestinos Ocupados"),
    TMP("TMP", "Timor Leste"),
    TGO("TGO", "Togo"),
    TON("TON", "Tonga"),
    TTO("TTO", "Trinidad and Tobago"),
    TUN("TUN", "Tunísia"),
    TKM("TKM", "Turcomenistão"),
    TUR("TUR", "Turquia"),
    TUV("TUV", "Tuvalu"),
    UKR("UKR", "Ucrânia"),
    UGA("UGA", "Uganda"),
    URY("URY", "Uruguai"),
    UZB("UZB", "Uzbequistão"),
    VUT("VUT", "Vanuatu"),
    VAT("VAT", "Vaticano"),
    VEN("VEN", "Venezuela"),
    VNM("VNM", "Vietnã"),
    ZMB("ZMB", "Zâmbia"),
    ZWE("ZWE", "Zimbábue");

    private String name;
    private String code;

    Country(String code, String name) {
        this.name = name;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public String getCode() {
        return code;
    }
};
